package com.lxvoice.domain.greendao.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BOOK".
 */
@Entity
public class Book {

    @Id
    private Long id;
    private String author;
    private String type;
    private Long text_number;
    private String name;
    private String depict;
    private java.util.Date ctime;
    private java.util.Date utime;

    @Generated(hash = 1839243756)
    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    @Generated(hash = 1903431478)
    public Book(Long id, String author, String type, Long text_number, String name, String depict, java.util.Date ctime, java.util.Date utime) {
        this.id = id;
        this.author = author;
        this.type = type;
        this.text_number = text_number;
        this.name = name;
        this.depict = depict;
        this.ctime = ctime;
        this.utime = utime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getText_number() {
        return text_number;
    }

    public void setText_number(Long text_number) {
        this.text_number = text_number;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDepict() {
        return depict;
    }

    public void setDepict(String depict) {
        this.depict = depict;
    }

    public java.util.Date getCtime() {
        return ctime;
    }

    public void setCtime(java.util.Date ctime) {
        this.ctime = ctime;
    }

    public java.util.Date getUtime() {
        return utime;
    }

    public void setUtime(java.util.Date utime) {
        this.utime = utime;
    }

}
