package com.lxvoice.domain.greendao.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NOTE".
 */
@Entity
public class Note {

    @Id
    private Long id;
    private Long book_id;
    private String title;
    private String context;
    private java.util.Date ctime;
    private java.util.Date utime;

    @Generated(hash = 1272611929)
    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    @Generated(hash = 596323158)
    public Note(Long id, Long book_id, String title, String context, java.util.Date ctime, java.util.Date utime) {
        this.id = id;
        this.book_id = book_id;
        this.title = title;
        this.context = context;
        this.ctime = ctime;
        this.utime = utime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBook_id() {
        return book_id;
    }

    public void setBook_id(Long book_id) {
        this.book_id = book_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContext() {
        return context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    public java.util.Date getCtime() {
        return ctime;
    }

    public void setCtime(java.util.Date ctime) {
        this.ctime = ctime;
    }

    public java.util.Date getUtime() {
        return utime;
    }

    public void setUtime(java.util.Date utime) {
        this.utime = utime;
    }

}
